### ISSUE TITLE
Error when reconciling cluster that uses cluster class

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/cluster-api-addon-provider-fleet#21]
When the provider reconciles the following cluster definition:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster1
  namespace: default
  labels:
    cni: kindnet
    env: "dev"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  topology:
    class: quick-start
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
    - name: imageRepository
      value: ""
    - name: etcdImageTag
      value: ""
    - name: coreDNSImageTag
      value: ""
    - name: podSecurityStandard
      value:
        audit: restricted
        enabled: true
        enforce: baseline
        warn: restricted
    version: v1.28.0
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
```

I am seeing the following error:

```
2024-04-24T08:45:30.604910Z  WARN kube_client::client: {"apiVersion":"cluster.x-k8s.io/v1beta1","items":[{"apiVersion":"cluster.x-k8s.io/v1beta1","kind":"Cluster","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cluster.x-k8s.io/v1beta1\",\"kind\":\"Cluster\",\"metadata\":{\"annotations\":{},\"labels\":{\"cni\":\"kindnet\",\"env\":\"dev\"},\"name\":\"cluster1\",\"namespace\":\"default\"},\"spec\":{\"clusterNetwork\":{\"pods\":{\"cidrBlocks\":[\"192.168.0.0/16\"]},\"serviceDomain\":\"cluster.local\",\"services\":{\"cidrBlocks\":[\"10.128.0.0/12\"]}},\"topology\":{\"class\":\"quick-start\",\"controlPlane\":{\"metadata\":{},\"replicas\":1},\"variables\":[{\"name\":\"imageRepository\",\"value\":\"\"},{\"name\":\"etcdImageTag\",\"value\":\"\"},{\"name\":\"coreDNSImageTag\",\"value\":\"\"},{\"name\":\"podSecurityStandard\",\"value\":{\"audit\":\"restricted\",\"enabled\":true,\"enforce\":\"baseline\",\"warn\":\"restricted\"}}],\"version\":\"v1.28.0\",\"workers\":{\"machineDeployments\":[{\"class\":\"default-worker\",\"name\":\"md-0\",\"replicas\":1}]}}}}\n"},"creationTimestamp":"2024-04-24T06:55:48Z","finalizers":["cluster.cluster.x-k8s.io"],"generation":3,"labels":{"cluster.x-k8s.io/cluster-name":"cluster1","cni":"kindnet","env":"dev","topology.cluster.x-k8s.io/owned":""},"managedFields":[{"apiVersion":"cluster.x-k8s.io/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{"f:cluster.x-k8s.io/cluster-name":{},"f:topology.cluster.x-k8s.io/owned":{}}},"f:spec":{"f:controlPlaneRef":{},"f:infrastructureRef":{}}},"manager":"capi-topology","operation":"Apply","time":"2024-04-24T06:55:48Z"},{"apiVersion":"cluster.x-k8s.io/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:cni":{},"f:env":{}}},"f:spec":{".":{},"f:clusterNetwork":{".":{},"f:pods":{".":{},"f:cidrBlocks":{}},"f:serviceDomain":{},"f:services":{".":{},"f:cidrBlocks":{}}},"f:topology":{".":{},"f:class":{},"f:controlPlane":{".":{},"f:metadata":{},"f:replicas":{}},"f:variables":{},"f:version":{},"f:workers":{".":{},"f:machineDeployments":{}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2024-04-24T06:55:48Z"},{"apiVersion":"cluster.x-k8s.io/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:finalizers":{".":{},"v:\"cluster.cluster.x-k8s.io\"":{}}},"f:spec":{"f:controlPlaneEndpoint":{"f:host":{},"f:port":{}}}},"manager":"manager","operation":"Update","time":"2024-04-24T06:55:48Z"},{"apiVersion":"cluster.x-k8s.io/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:conditions":{},"f:controlPlaneReady":{},"f:infrastructureReady":{},"f:observedGeneration":{},"f:phase":{}}},"manager":"manager","operation":"Update","subresource":"status","time":"2024-04-24T06:57:07Z"}],"name":"cluster1","namespace":"default","resourceVersion":"5371","uid":"d8f0cf88-38f8-4360-8e25-c55d8c727905"},"spec":{"clusterNetwork":{"pods":{"cidrBlocks":["192.168.0.0/16"]},"serviceDomain":"cluster.local","services":{"cidrBlocks":["10.128.0.0/12"]}},"controlPlaneEndpoint":{"host":"172.19.0.3","port":6443},"controlPlaneRef":{"apiVersion":"controlplane.cluster.x-k8s.io/v1beta1","kind":"KubeadmControlPlane","name":"cluster1-cdhv9","namespace":"default"},"infrastructureRef":{"apiVersion":"infrastructure.cluster.x-k8s.io/v1beta1","kind":"DockerCluster","name":"cluster1-vdwrk","namespace":"default"},"topology":{"class":"quick-start","controlPlane":{"metadata":{},"replicas":1},"variables":[{"name":"imageRepository","value":""},{"name":"etcdImageTag","value":""},{"name":"coreDNSImageTag","value":""},{"name":"podSecurityStandard","value":{"audit":"restricted","enabled":true,"enforce":"baseline","warn":"restricted"}}],"version":"v1.28.0","workers":{"machineDeployments":[{"class":"default-worker","metadata":{},"name":"md-0","replicas":1}]}}},"status":{"conditions":[{"lastTransitionTime":"2024-04-24T06:56:53Z","status":"True","type":"Ready"},{"lastTransitionTime":"2024-04-24T06:56:53Z","status":"True","type":"ControlPlaneInitialized"},{"lastTransitionTime":"2024-04-24T06:56:53Z","status":"True","type":"ControlPlaneReady"},{"lastTransitionTime":"2024-04-24T06:55:48Z","status":"True","type":"InfrastructureReady"},{"lastTransitionTime":"2024-04-24T06:55:48Z","status":"True","type":"TopologyReconciled"}],"controlPlaneReady":true,"infrastructureReady":true,"observedGeneration":3,"phase":"Provisioned"}}],"kind":"ClusterList","metadata":{"continue":"","resourceVersion":"35668"}}
, Error("invalid type: string \"\", expected a map", line: 1, column: 3559)
```

Looking at the column position it relates to the empty value in this part:

```yaml
{"name":"imageRepository","value":""}
```

And then looking at the  where value is defined:
- Go source https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/cluster_types.go#L327C2-L327C43
- crd https://github.com/kubernetes-sigs/cluster-api/blob/main/config/crd/bases/cluster.x-k8s.io_clusters.yaml#L1117-L1126

I am using kpoium v0.18.0
