### ISSUE TITLE
Store the state of `Fleet` feature flags in a `ConfigMap` with a configurable name

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher-sandbox/cluster-api-addon-provider-fleet#240]
We need to define a path to specify applied feature flags externally from the CAAPF `FleetAddonConfig` resource.

This should allow to perform fleet chart patch tentatively based on the `ConfigMap` state for the upstream installation, and will not require to store state in condition, making it purely informational. It would also benefit `rancher` based installation, when the `ConfigMap` used is named `rancher-config`.

`ConfigMap` content should be in the form of:

```yaml
apiVersion: v1
kind: ConfigMap
data:
  fleet: |
    extraEnv:
    - name: EXPERIMENTAL_OCI_STORAGE
      value: "true"
```
which would match `rancher-config` content expectations.

```yaml
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: FleetAddonConfig
metadata:
  name: fleet-addon-config
spec:
  config:
    featureGates:
      configMap:               # ConfigMap state configuration settings (optional)
        ref:                # Optional reference override. Can default to `cattle-fleet-system/fleet-flags`
          kind: ConfigMap
          apiVersion: v1
          name: rancher-config
          namespace: cattle-system
      experimentalOciStorage: true   # Enables experimental OCI storage support
      experimentalHelmOps: true      # Enables experimental Helm operations support
```
